chore: 릴리즈 노트 생성 단계 추가 (#15)
- 이미 배포된 앱의 버전 코드에 맞춰 수정

diff --git a/.github/workflows/android-cd.yml b/.github/workflows/android-cd.yml
--- a/.github/workflows/android-cd.yml
+++ b/.github/workflows/android-cd.yml
@@ -10,13 +10,16 @@ jobs:
 
     runs-on: ubuntu-latest
 
+    permissions:
+      contents: write
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: setup JDK 17
+      - name: Setup JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
@@ -35,6 +38,18 @@ jobs:
       - name: Generate squadbuilder.jks
         run: echo '${{ secrets.JAVA_KEY_STORE }}' | base64 -d > ./squadbuilder.jks
 
+      - name: Extract Version Name from libs.versions.toml
+        id: extract_version_name
+        run: |
+          set -euo pipefail
+          VERSION=$(grep "versionName" gradle/libs.versions.toml | sed -E 's/.*versionName\s*=\s*"([^"]+)".*/\1/')
+          if [[ -z "$VERSION" ]]; then
+            echo "Error: Not Found versionName" >&2
+            exit 1
+          fi
+          echo "version=v${VERSION}" >> "$GITHUB_OUTPUT"
+          echo "Version extracted from toml: v${VERSION}"
+
       - name: Generate Simple Release Note
         id: release_note_content
         run: |
@@ -47,6 +62,13 @@ jobs:
 
       - name: Build Release AAB
         run: ./gradlew :app:bundleRelease
+
+      - name: Create Github Release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: ${{ steps.extract_version_name.outputs.version }}
+          release_name: ${{ steps.extract_version_name.outputs.version }}
+          generate_release_notes: true
 
       - name: Deploy to Google Play Console (Fastlane/Action)
         uses: rymndhng/fastlane-play-store-action@v1
